### ISSUE TITLE
contents of dir.php?

### ISSUE THREAD

**Issue by sublok** [Terrance/IngressDualMap#2]
What was the php code for download?

**Comment by Terrance** [comment]
(Apologies, this issue managed to slip by without me noticing...)

All it does is print out CSV for the available lists.  Columns are display name, location, filename, timestamp.  The script I use looks like this:

``` php
<?
$db = array(
    // "<filename>" => array("<display name>", "<location>")
);
header("Content-Type: text/csv");
foreach (glob("*.csv") as $file) {
    print("\"" . implode("\",\"", array($db[$file][0], $db[$file][1],
          $file, date("d/m/Y H:i", filemtime($file)))) . "\"\n");
}
```
